packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  '@sveltejs/vite-plugin-svelte': '^3.1.0'
  '@tanstack/table-core': '^8.17.3'
  '@tsconfig/svelte': '^5.0.5'
  '@uwdata/mosaic-core': '^0.20.1'
  '@uwdata/mosaic-sql': '^0.20.1'
  '@uwdata/vgplot': '^0.20.1'
  '@vitejs/plugin-react': '^5.1.0'
  prettier-plugin-svelte: '^3.4.0'
  rimraf: '^6.0.1'
  svelte-check: '^3.8.6'
  typescript: '^5.4.5'
  vite: '^7.1.12'
onlyBuiltDependencies:
  - esbuild
