packages:
  - packages/*
  - examples/react/*

catalog:
  '@eslint-react/eslint-plugin': ^2.12.4
  '@playwright/test': ^1.58.2
  '@tanstack/eslint-config': ^0.3.4
  '@tanstack/vite-config': ^0.4.3
  '@tanstack/store': ^0.8.0
  '@tanstack/react-store': ^0.8.0
  '@tanstack/table-core': ^8.17.3
  '@types/cors': ^2.8.17
  '@types/express': ^5.0.0
  '@types/node': ^25.0.8
  '@uwdata/mosaic-core': ^0.21.1
  '@uwdata/mosaic-sql': ^0.21.1
  '@uwdata/vgplot': ^0.21.1
  '@vitejs/plugin-react': ^5.1.4
  cors: 2.8.6
  eslint: ^9.39.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-unused-imports: ^4.4.1
  express: 4.22.1
  jsdom: ^27.4.0
  node-fetch: 3.3.2
  rimraf: ^6.1.0
  typescript: ^5.9.3
  typescript-eslint: ^8.55.0
  vite: ^7.1.12
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
