packages:
  - packages/*
  - examples/react/*

catalog:
  '@eslint-react/eslint-plugin': ^2.2.4
  '@tanstack/store': '^0.8.0'
  '@tanstack/react-store': ^0.8.0
  '@tanstack/table-core': ^8.17.3
  '@uwdata/mosaic-core': ^0.21.1
  '@uwdata/mosaic-sql': ^0.21.1
  '@uwdata/vgplot': ^0.21.1
  '@vitejs/plugin-react': ^5.1.0
  eslint: ^9.39.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-unused-imports: ^4.3.0
  rimraf: ^6.1.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.2
  vite: ^7.1.12

onlyBuiltDependencies:
  - esbuild
