packages:
  - packages/*
  - examples/react/*

catalog:
  '@eslint-react/eslint-plugin': ^2.8.1
  '@playwright/test': ^1.58.1
  '@tanstack/eslint-config': ^0.3.4
  '@tanstack/vite-config': ^0.4.3
  '@tanstack/store': ^0.8.0
  '@tanstack/react-store': ^0.8.0
  '@tanstack/table-core': ^8.17.3
  '@types/node': ^25.0.8
  '@uwdata/mosaic-core': ^0.21.1
  '@uwdata/mosaic-sql': ^0.21.1
  '@uwdata/vgplot': ^0.21.1
  '@vitejs/plugin-react': ^5.1.0
  eslint: ^9.39.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-unused-imports: ^4.3.0
  jsdom: ^27.4.0
  rimraf: ^6.1.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vite: ^7.1.12
  vitest: ^4.0.18

onlyBuiltDependencies:
  - esbuild
