// This file contains a simple React wrapper component that safely renders an HTMLElement
// generated by a vgplot specification into the React DOM using a ref and a layout effect.
import React, { useLayoutEffect, useRef } from 'react';

interface VgplotProps {
  plot: HTMLElement | null;
}

export function Vgplot({ plot }: VgplotProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const container = containerRef.current;
    if (container && plot) {
      container.innerHTML = ''; // Clear previous plot
      container.appendChild(plot);
    }
    return () => {
      if (container) {
        container.innerHTML = ''; // Clean up on unmount
      }
    };
  }, [plot]);

  return <div ref={containerRef} />;
}
